// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN:
//
//   dart tool/regenerate_hashes.dart <github release tag>
//

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:code_assets/code_assets.dart';
import 'package:crypto/crypto.dart';

/// GitHub repository hosting prebuilt release artifacts and SLSA provenance attestations.
const repository = 'google/scientific_dart';

/// Release tag for prebuilt `ndarray` binaries.
const version = 'artifacts-v0.2.0';

/// Combined SHA-256 digest of `hook/` native source files at [version].
const nativeSourceHash =
    '53ba4503c7edde11b7dbab5e64006a524222a9c49e594a19807ea93bcc2366c6';

/// ASCII marker prefix embedded in compiled `ndarray` binaries.
const sourceHashMarkerPrefix = 'NDARRAY_SOURCE_HASH=';

/// Extracts the 64-character lowercase hex SHA-256 digest embedded after
/// [sourceHashMarkerPrefix] in [bytes], or returns `null` if no marker is
/// present.
String? extractEmbeddedSourceHash(Uint8List bytes) {
  final prefix = sourceHashMarkerPrefix.codeUnits;
  final prefixLen = prefix.length;
  const hashLen = 64;
  final limit = bytes.length - (prefixLen + hashLen);
  outer:
  for (var i = 0; i <= limit; i++) {
    for (var j = 0; j < prefixLen; j++) {
      if (bytes[i + j] != prefix[j]) continue outer;
    }
    final start = i + prefixLen;
    for (var k = 0; k < hashLen; k++) {
      final b = bytes[start + k];
      final isDigit = b >= 0x30 && b <= 0x39;
      final isHexLower = b >= 0x61 && b <= 0x66;
      if (!isDigit && !isHexLower) continue outer;
    }
    return String.fromCharCodes(bytes, start, start + hashLen);
  }
  return null;
}

/// Verifies that [bytes] of a prebuilt `ndarray` artifact correspond to
/// [currentSourceHash].
///
/// It is an error if [currentSourceHash] differs from [nativeSourceHash], if
/// an embedded [sourceHashMarkerPrefix] marker is present and does not match
/// [currentSourceHash], or if the marker is missing in a release after
/// `artifacts-v0.0.2`.
void verifyArtifactSourceHash(
  Uint8List bytes, {
  required String currentSourceHash,
  String releaseVersion = version,
}) {
  if (currentSourceHash != nativeSourceHash) {
    throw StateError(
      'Prebuilt ndarray binary for release $releaseVersion is out of date with '
      'native sources in hook/ (pinned: $nativeSourceHash, '
      'current: $currentSourceHash).',
    );
  }
  final embeddedHash = extractEmbeddedSourceHash(bytes);
  if (embeddedHash == null) {
    if (releaseVersion != 'artifacts-v0.0.2') {
      throw StateError(
        'Prebuilt ndarray binary for release $releaseVersion is missing '
        'embedded $sourceHashMarkerPrefix<sha256> marker.',
      );
    }
    return;
  }
  if (embeddedHash != currentSourceHash) {
    throw StateError(
      'Embedded source hash in prebuilt ndarray binary ($embeddedHash) does '
      'not match hook/ source hash ($currentSourceHash).',
    );
  }
}

/// Lists the tracked native source files in `hook/` under [packageRoot].
List<File> nativeSourceFiles(Uri packageRoot) {
  final hookDir = Directory.fromUri(packageRoot.resolve('hook/'));
  if (!hookDir.existsSync()) return const [];
  final files = hookDir.listSync().whereType<File>().where((file) {
    final name = file.uri.pathSegments.last;
    return name.endsWith('.dart') ||
        name.endsWith('.c') ||
        name.endsWith('.cpp') ||
        name.endsWith('.h') ||
        name.endsWith('.def');
  }).toList();
  for (final relPath in const [
    'third_party/miniz/miniz.c',
    'third_party/miniz/miniz.h',
  ]) {
    final extra = File.fromUri(packageRoot.resolve(relPath));
    if (extra.existsSync()) {
      files.add(extra);
    }
  }
  files.sort(
    (a, b) => a.uri.pathSegments.last.compareTo(b.uri.pathSegments.last),
  );
  return files;
}

/// Computes the combined SHA-256 digest of `hook/` native source files under [packageRoot].
String computeNativeSourceHash(Uri packageRoot) {
  final buffer = StringBuffer();
  for (final file in nativeSourceFiles(packageRoot)) {
    final name = file.uri.pathSegments.last;
    final normalized = file.readAsStringSync().replaceAll('\r\n', '\n');
    final fileDigest = sha256.convert(utf8.encode(normalized)).toString();
    buffer.writeln('$name:$fileDigest');
  }
  return sha256.convert(utf8.encode(buffer.toString())).toString();
}

/// Canonical release artifact filename for `(os, arch)`.
String ndarrayArtifactName(OS os, Architecture arch) {
  final ext = switch (os) {
    OS.windows => 'dll',
    OS.macOS || OS.iOS => 'dylib',
    _ => 'so',
  };
  return 'ndarray-${os.name}-${arch.name}.$ext';
}

/// SHA-256 digests for prebuilt `ndarray` binaries indexed by `(OS, Architecture)`.
final fileHashes = <(OS, Architecture), String>{
  (OS.linux, Architecture.x64):
      '9bd78aa2ae4a7556b76e4ba3640341a78bdeda974bd44862396122754760032b',
  (OS.linux, Architecture.arm64):
      'c8e2edc898e4a236cef0c85845a4ad864e64681d28d1aa587df343dba96462c4',
  (OS.macOS, Architecture.arm64):
      '614199d35460f0ffc3c29e9a6e7f2f15b5fb0f050f16e5a4de7d8bb94909fdf1',
  (OS.macOS, Architecture.x64):
      'f99b1d8900c1982cadc2e8be2badd6c50793e7d0382a6aa08fcac16bf5be7b69',
  (OS.windows, Architecture.x64):
      '7afb30d5bd2fa03171c0a88b34d587a27f569ba90f6cddd593de96c78ae79401',
};
