// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN:
//
//   dart tool/regenerate_hashes.dart <github release tag>
//

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:code_assets/code_assets.dart';
import 'package:crypto/crypto.dart';

/// GitHub repository hosting prebuilt release artifacts and SLSA provenance attestations.
const repository = 'google/scientific_dart';

/// Release tag for prebuilt `pocketfft` binaries.
const version = 'artifacts-v0.2.0';

/// Combined SHA-256 digest of `hook/` native source files at [version].
const nativeSourceHash =
    '75e074691c4d751b31c1bff0004d275b6d3ea835d06f158157b6c4a128761d81';

/// ASCII marker prefix embedded in compiled `pocketfft` binaries.
const sourceHashMarkerPrefix = 'POCKETFFT_SOURCE_HASH=';

/// Extracts the 64-character lowercase hex SHA-256 digest embedded after
/// [sourceHashMarkerPrefix] in [bytes], or returns `null` if no marker is
/// present.
String? extractEmbeddedSourceHash(Uint8List bytes) {
  final prefix = sourceHashMarkerPrefix.codeUnits;
  final prefixLen = prefix.length;
  const hashLen = 64;
  final limit = bytes.length - (prefixLen + hashLen);
  outer:
  for (var i = 0; i <= limit; i++) {
    for (var j = 0; j < prefixLen; j++) {
      if (bytes[i + j] != prefix[j]) continue outer;
    }
    final start = i + prefixLen;
    for (var k = 0; k < hashLen; k++) {
      final b = bytes[start + k];
      final isDigit = b >= 0x30 && b <= 0x39;
      final isHexLower = b >= 0x61 && b <= 0x66;
      if (!isDigit && !isHexLower) continue outer;
    }
    return String.fromCharCodes(bytes, start, start + hashLen);
  }
  return null;
}

/// Verifies that [bytes] of a prebuilt `pocketfft` artifact correspond to
/// [currentSourceHash].
///
/// It is an error if [currentSourceHash] differs from [nativeSourceHash], if
/// an embedded [sourceHashMarkerPrefix] marker is present and does not match
/// [currentSourceHash], or if the marker is missing in a release after
/// `artifacts-v0.0.2`.
void verifyArtifactSourceHash(
  Uint8List bytes, {
  required String currentSourceHash,
  String releaseVersion = version,
}) {
  if (currentSourceHash != nativeSourceHash) {
    throw StateError(
      'Prebuilt pocketfft binary for release $releaseVersion is out of date with '
      'native sources in hook/ (pinned: $nativeSourceHash, '
      'current: $currentSourceHash).',
    );
  }
  final embeddedHash = extractEmbeddedSourceHash(bytes);
  if (embeddedHash == null) {
    if (releaseVersion != 'artifacts-v0.0.2') {
      throw StateError(
        'Prebuilt pocketfft binary for release $releaseVersion is missing '
        'embedded $sourceHashMarkerPrefix<sha256> marker.',
      );
    }
    return;
  }
  if (embeddedHash != currentSourceHash) {
    throw StateError(
      'Embedded source hash in prebuilt pocketfft binary ($embeddedHash) does '
      'not match hook/ source hash ($currentSourceHash).',
    );
  }
}

/// Lists the tracked native source files in `hook/` under [packageRoot].
List<File> nativeSourceFiles(Uri packageRoot) {
  final hookDir = Directory.fromUri(packageRoot.resolve('hook/'));
  if (!hookDir.existsSync()) return const [];
  final files = hookDir.listSync().whereType<File>().where((file) {
    final name = file.uri.pathSegments.last;
    return name.endsWith('.dart') ||
        name.endsWith('.c') ||
        name.endsWith('.cpp') ||
        name.endsWith('.h') ||
        name.endsWith('.def');
  }).toList();
  for (final relPath in const [
    'third_party/miniz/miniz.c',
    'third_party/miniz/miniz.h',
  ]) {
    final extra = File.fromUri(packageRoot.resolve(relPath));
    if (extra.existsSync()) {
      files.add(extra);
    }
  }
  files.sort(
    (a, b) => a.uri.pathSegments.last.compareTo(b.uri.pathSegments.last),
  );
  return files;
}

/// Computes the combined SHA-256 digest of `hook/` native source files under [packageRoot].
String computeNativeSourceHash(Uri packageRoot) {
  final buffer = StringBuffer();
  for (final file in nativeSourceFiles(packageRoot)) {
    final name = file.uri.pathSegments.last;
    final normalized = file.readAsStringSync().replaceAll('\r\n', '\n');
    final fileDigest = sha256.convert(utf8.encode(normalized)).toString();
    buffer.writeln('$name:$fileDigest');
  }
  return sha256.convert(utf8.encode(buffer.toString())).toString();
}

/// Canonical release artifact filename for `(os, arch)`.
String pocketfftArtifactName(OS os, Architecture arch) {
  final ext = switch (os) {
    OS.windows => 'dll',
    OS.macOS || OS.iOS => 'dylib',
    _ => 'so',
  };
  return 'pocketfft-${os.name}-${arch.name}.$ext';
}

/// SHA-256 digests for prebuilt `pocketfft` binaries indexed by `(OS, Architecture)`.
final fileHashes = <(OS, Architecture), String>{
  (OS.linux, Architecture.x64):
      '25427edf4e095e844e30e8a563ad36c43173b2153196746204523b2ff2bc0315',
  (OS.linux, Architecture.arm64):
      '85efe3238e7ed956c3da6f54c2282d26f59a19d016801f3db55b00f5268513e7',
  (OS.macOS, Architecture.arm64):
      '4f7beda3de31d02abc9dad57aed2d405a9b8b5e42bcd7b22e8f4a7b05e914256',
  (OS.macOS, Architecture.x64):
      'd9fb2ad122c825997a63cc84138d137c411e0d65c373787ff59754ede577b0e9',
  (OS.windows, Architecture.x64):
      '39a55d5c1c53ca5ae63b6d683bc5cccdc8274fc0121feb506e145c989a190198',
};
