# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: scientific_dart_workspace
environment:
  sdk: ^3.10.0
workspace:
  - pkgs/openblas
  - pkgs/ndarray
  - pkgs/pocketfft
  - pkgs/guitar_tuner
  - pkgs/ndarray_ma
  - pkgs/notebook
  - pkgs/code_editor
  - pkgs/symbolic_dart
  - pkgs/resource_scope
  - pkgs/gpuarray
  - pkgs/scientific_dart_analysis_plugin
dependencies:
  args: ^2.7.0
  code_assets: '>=1.0.0 <3.0.0'
  crypto: ^3.0.7
  hooks: '>=1.0.3 <3.0.0'
  http: ^1.6.0

dev_dependencies:
  ffigen: ^20.1.1

hooks:
  user_defines:
    ndarray:
      buildMode: source
    openblas:
      buildMode: source
    pocketfft:
      buildMode: source
    symbolic_dart:
      buildMode: source
    gpuarray:
      buildMode: fetch
