// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN:
//
//   dart tool/regenerate_hashes.dart <github release tag>
//

import 'package:code_assets/code_assets.dart';

/// GitHub repository hosting prebuilt release artifacts and SLSA provenance attestations.
const repository = 'google/scientific_dart';

/// Release tag for prebuilt `symbolic_dart` binaries.
const version = 'artifacts-v0.1.0';

/// Canonical release artifact filename for `(os, arch, libraryKind)`.
///
/// [libraryKind] is either `'flint'` or `'symengine'`.
String symbolicDartArtifactName(OS os, Architecture arch, String libraryKind) {
  final ext = switch (os) {
    OS.windows => 'dll',
    OS.macOS || OS.iOS => 'dylib',
    _ => 'so',
  };
  return '$libraryKind-${os.name}-${arch.name}.$ext';
}

/// SHA-256 digests for prebuilt `symbolic_dart` binaries indexed by `(OS, Architecture, libraryKind)`.
const fileHashes = <(OS, Architecture, String), String>{
  (OS.linux, Architecture.x64, 'flint'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.linux, Architecture.x64, 'symengine'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.linux, Architecture.arm64, 'flint'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.linux, Architecture.arm64, 'symengine'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.macOS, Architecture.arm64, 'flint'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.macOS, Architecture.arm64, 'symengine'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.macOS, Architecture.x64, 'flint'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.macOS, Architecture.x64, 'symengine'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.windows, Architecture.x64, 'flint'):
      '0000000000000000000000000000000000000000000000000000000000000000',
  (OS.windows, Architecture.x64, 'symengine'):
      '0000000000000000000000000000000000000000000000000000000000000000',
};
