// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOGENERATED BY `tool/regenerate_hashes.dart`. TO UPDATE, RUN:
//
//   dart tool/regenerate_hashes.dart <github release tag>
//

import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:code_assets/code_assets.dart';
import 'package:crypto/crypto.dart';

/// GitHub repository hosting prebuilt release artifacts and SLSA provenance attestations.
const repository = 'google/scientific_dart';

/// Release tag for prebuilt `openblas` binaries.
const version = 'artifacts-v0.2.0';

/// Combined SHA-256 digest of `hook/` native source files at [version].
const nativeSourceHash =
    '4b7f2d5c6fb05d4977d6641c63dca911acb67547e15344d5d88e85d7672d3a0d';

/// ASCII marker prefix embedded in compiled `openblas` extension binaries.
const sourceHashMarkerPrefix = 'OPENBLAS_SOURCE_HASH=';

/// Extracts the 64-character lowercase hex SHA-256 digest embedded after
/// [sourceHashMarkerPrefix] in [bytes], or returns `null` if no marker is
/// present.
String? extractEmbeddedSourceHash(Uint8List bytes) {
  final prefix = sourceHashMarkerPrefix.codeUnits;
  final prefixLen = prefix.length;
  const hashLen = 64;
  final limit = bytes.length - (prefixLen + hashLen);
  outer:
  for (var i = 0; i <= limit; i++) {
    for (var j = 0; j < prefixLen; j++) {
      if (bytes[i + j] != prefix[j]) continue outer;
    }
    final start = i + prefixLen;
    for (var k = 0; k < hashLen; k++) {
      final b = bytes[start + k];
      final isDigit = b >= 0x30 && b <= 0x39;
      final isHexLower = b >= 0x61 && b <= 0x66;
      if (!isDigit && !isHexLower) continue outer;
    }
    return String.fromCharCodes(bytes, start, start + hashLen);
  }
  return null;
}

/// Verifies that [bytes] of a prebuilt `openblas` artifact correspond to
/// [currentSourceHash].
///
/// It is an error if [currentSourceHash] differs from [nativeSourceHash], if
/// an embedded [sourceHashMarkerPrefix] marker is present and does not match
/// [currentSourceHash], or if the marker is missing in a release after
/// `artifacts-v0.0.2`.
void verifyArtifactSourceHash(
  Uint8List bytes, {
  required String currentSourceHash,
  String releaseVersion = version,
}) {
  if (currentSourceHash != nativeSourceHash) {
    throw StateError(
      'Prebuilt openblas binary for release $releaseVersion is out of date with '
      'native sources in hook/ (pinned: $nativeSourceHash, '
      'current: $currentSourceHash).',
    );
  }
  final embeddedHash = extractEmbeddedSourceHash(bytes);
  if (embeddedHash == null) {
    if (releaseVersion != 'artifacts-v0.0.2') {
      throw StateError(
        'Prebuilt openblas binary for release $releaseVersion is missing '
        'embedded $sourceHashMarkerPrefix<sha256> marker.',
      );
    }
    return;
  }
  if (embeddedHash != currentSourceHash) {
    throw StateError(
      'Embedded source hash in prebuilt openblas binary ($embeddedHash) does '
      'not match hook/ source hash ($currentSourceHash).',
    );
  }
}

/// Lists the tracked native source files in `hook/` under [packageRoot].
List<File> nativeSourceFiles(Uri packageRoot) {
  final hookDir = Directory.fromUri(packageRoot.resolve('hook/'));
  if (!hookDir.existsSync()) return const [];
  final files = hookDir.listSync().whereType<File>().where((file) {
    final name = file.uri.pathSegments.last;
    return name.endsWith('.dart') ||
        name.endsWith('.c') ||
        name.endsWith('.cpp') ||
        name.endsWith('.h') ||
        name.endsWith('.def');
  }).toList();
  files.sort(
    (a, b) => a.uri.pathSegments.last.compareTo(b.uri.pathSegments.last),
  );
  return files;
}

/// Computes the combined SHA-256 digest of `hook/` native source files under [packageRoot].
String computeNativeSourceHash(Uri packageRoot) {
  final buffer = StringBuffer();
  for (final file in nativeSourceFiles(packageRoot)) {
    final name = file.uri.pathSegments.last;
    final normalized = file.readAsStringSync().replaceAll('\r\n', '\n');
    final fileDigest = sha256.convert(utf8.encode(normalized)).toString();
    buffer.writeln('$name:$fileDigest');
  }
  return sha256.convert(utf8.encode(buffer.toString())).toString();
}

/// Canonical release artifact filename for `(os, arch, libraryKind)`.
///
/// [libraryKind] is either `'openblas'` or `'openblas_extensions'`.
String openblasArtifactName(OS os, Architecture arch, String libraryKind) {
  final ext = switch (os) {
    OS.windows => 'dll',
    OS.macOS || OS.iOS => 'dylib',
    _ => 'so',
  };
  return '$libraryKind-${os.name}-${arch.name}.$ext';
}

/// SHA-256 digests for prebuilt `openblas` binaries indexed by `(OS, Architecture, libraryKind)`.
final fileHashes = <(OS, Architecture, String), String>{
  (OS.linux, Architecture.x64, 'openblas'):
      '89a5bd9a56f29babae59c73f1d37cd961036664ba0b9d7fa55b1dcc29321d535',
  (OS.linux, Architecture.x64, 'openblas_extensions'):
      '046259f033276e79792749e293c27784510e91e71335e197379eb7675a9cafc4',
  (OS.linux, Architecture.arm64, 'openblas'):
      'df645117ecf5aadc53aa2d99a6fc72b7fff1bb7efbb3af4c91e8d743c1b3fb06',
  (OS.linux, Architecture.arm64, 'openblas_extensions'):
      '68a0b3b80039e4094323d9bacb4c7612a80b7bb1b58a3fd41c5d849944371584',
  (OS.macOS, Architecture.arm64, 'openblas'):
      '02eba7b23489e640f376c2d27f0ed6e55c40a6f19e792b49973fd2858cadda78',
  (OS.macOS, Architecture.arm64, 'openblas_extensions'):
      '8fb6cfef5d079ded35a8ede40e5e07c17647006ab06c8bd5549b3d37f44a034d',
  (OS.macOS, Architecture.x64, 'openblas'):
      '46d32d61c8e9f97a5c759802c75eb1e9f2af1010fb092f98d61f39275c0342e0',
  (OS.macOS, Architecture.x64, 'openblas_extensions'):
      '6a59534f0a871598296fc898df411dd9ca9a454a2d2e890eed4dec92475bacae',
  (OS.windows, Architecture.x64, 'openblas'):
      'c8b6f93012b81eb5775955006a1a363d720ba2013b5262052944763e0a736346',
  (OS.windows, Architecture.x64, 'openblas_extensions'):
      '80d84126c57346c5f32e3cc73af88eb92d4636385f97fd8450ef07fe643affaf',
};
